version: "3.8"
services:
  frontend:
    build: 
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - 80:80
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./front-end:/app/front-end
    ports:
      - 3000:3000
    depends_on:
      - frontend
