# ORIGINAL:
#
# version: "3.8"
# services:
#   frontend:
#     build: ./front-end
#     ports:
#       - 80:80
#   api:
#     build: ./api
#     ports:
#       - 3000:3000


# WORKS WITH ONLY ONE CONTAINER:

version: "3.8"
services:
#   frontend:
#     build: ./front-end
#     ports:
#       - 80:80
  api:
    build: ./api
    volumes:
      - ./front-end:/app/front-end
    ports:
      - 3000:3000


# version: "3.8"
# services:
#   frontend:
#     build: ./front-end
#     ports:
#       - 80:80
#   api:
#     build: ./api
#     volumes:
#       - ./front-end:/app/front-end
#     ports:
#       - 3000:3000

# version: "3.8"
# services:
#   frontend:
#     build: ./front-end
#     ports:
#       - 80:80
#     volumes:
#       - ./front-end:/usr/share/nginx/html
#   api:
#     build: ./api
#     ports:
#       - 3000:3000
#     environment:
#       - FRONTEND_HOST=frontend
