# With Proxy
version: "3.6"
services:
  frontend:
    build: 
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - 80:80
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - frontend
  proxy:
    build:
      context: ./proxy  
      dockerfile: Dockerfile 
    ports:
      - 4000:4000  
    depends_on:
      - frontend
      - api

# Before Proxy
# version: "3.6"
# services:
#   frontend:
#     build: 
#       context: ./front-end
#       dockerfile: Dockerfile
#     ports:
#       - 80:80
#   api:
#     build:
#       context: ./api
#       dockerfile: Dockerfile
#     ports:
#       - 3000:3000
#     depends_on:
#       - frontend


